In [58]:
import numpy as np

### Accessing/Changing specific elements, rows, columns, etc.

In [59]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [60]:
# get a specific element -> different from normal list operation -> list_x[r, c]
var_a1 = a[1, 5]
var_a2 = a[1, -2]

print(var_a1, var_a2)

13 13


In [61]:
# get specific row
var_a3 = a[0]
var_a4 = a[0, :]
var_a5 = a[0, 0:]

print(var_a5)

[1 2 3 4 5 6 7]


In [62]:
# get specific portion of row
a[1, 2:6]

array([10, 11, 12, 13])

In [63]:
# get specific column 
    # array format in numpy -> [row, column]
a[:, 2]

array([ 3, 10])

In [64]:
# using step size
a[:, 1::2]

array([[ 2,  4,  6],
       [ 9, 11, 13]])

In [65]:
# change an element
a [0, 3] = 400
print(a)

a[:, 2] = [1000,2000]
print(a)

[[  1   2   3 400   5   6   7]
 [  8   9  10  11  12  13  14]]
[[   1    2 1000  400    5    6    7]
 [   8    9 2000   11   12   13   14]]


In [66]:
# 3-d example
b = np.array([[[1,2], [3,4]], [[5,6], [7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [67]:
# get specific element -> work outside in
b[1, 0, 1]


6