In [5]:
import numpy as np

Initializing different types of arrays

In [13]:
# all 0s matrix
np.zeros(5)
np.zeros((2,3))
np.zeros((3,2,2))

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [16]:
# all 1s matrix
np.ones((4,2,2), dtype='int16')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int16)

In [26]:
# any other number
np.full((2,2), 56, dtype='float32')

array([[56., 56.],
       [56., 56.]], dtype=float32)

In [31]:
example = np.array([[1,2,3], [2,3,4]])

np.full(example.shape, 100)
np.full_like(example, 23)

array([[100, 100, 100],
       [100, 100, 100]])

In [36]:
# random decimal numbers
np.random.rand(2, 3)
np.random.random_sample(example.shape)

array([[0.38659821, 0.64572235, 0.45563288],
       [0.66262526, 0.80203574, 0.47565932]])

In [51]:
# random integer values
np.random.randint(2, 7, size=(3,3))

array([[3, 6, 3],
       [2, 4, 4],
       [4, 6, 3]])

In [52]:
# identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [55]:
# repeat
a = np.array([[1,2,3]])
np.repeat(a, 3, axis=0)

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [67]:
# CHALLENGE

ones = np.ones((5,5), dtype='int16')

zeros = np.zeros((3,3), dtype='int16')
zeros [1,1] = 9

ones[1:4, 1:4] = zeros

print(ones)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


be careful when copying arrays

In [70]:
a = np.array([1,2,3])
b = a.copy()

print(b)

[1 2 3]
