In [17]:
import numpy as np

Mathematics of NumPy

In [18]:
a =  np.array([10,20,30,40])
print(a)

[10 20 30 40]


In [19]:
# add a number with array will add that number to all elements of array
a + 2

array([12, 22, 32, 42])

In [20]:
# above method is not possible in normal lists
"""
b = [1,2,3,4]
b + 2
"""

'\nb = [1,2,3,4]\nb + 2\n'

In [21]:
# subtraction
a - 2

array([ 8, 18, 28, 38])

In [22]:
# multiplication
a * 2

array([20, 40, 60, 80])

In [23]:
# division
a / 2
a // 2

array([ 5, 10, 15, 20], dtype=int32)

In [24]:
# addition of two arrays
b = np.array([100,200,300,400])
a + b

array([110, 220, 330, 440])

In [25]:
# power
a ** 2

array([ 100,  400,  900, 1600], dtype=int32)

In [26]:
# sin, cos, tan -> etc : all sorts of math functions
np.sin(a)
np.cos(a)
np.tan(a)

array([ 0.64836083,  2.23716094, -6.4053312 , -1.11721493])

NumPy docs:

https://docs.scipy.org/doc/numpy/reference/

Linear Algebra

In [27]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

"""
a * b -> does not work since both matrices are of different shapes
"""

# matrix multiplication in numpy
np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [28]:
# get determinant of a mattrix
c = np.identity(3)
print(c)
np.linalg.det(c)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


1.0

Linear Algebra related numpy

https://docs.scipy.org/doc/numpy/reference/routines.linalg.html

#Determinant
#Inverse
#Dot product
#Inner product
#Matrix power
#Eigen values
#Matrix norm
#Trace
#Singular vector decomposition

Statistics

In [29]:
stats = np.array([[1,2,3], [4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
# min, max
np.min(stats)
np.max(stats)

6

In [31]:
# min, max on axis

# axis = 0 -> indicates row
# axis = 1 -> indicates column

# https://www.sharpsightlabs.com/blog/numpy-axes-explained/

np.min(stats, axis=1)
np.max(stats, axis=0)

array([4, 5, 6])

In [33]:
# sum
print(stats)
np.sum(stats)


[[1 2 3]
 [4 5 6]]


21