In [43]:
import numpy as np

### Miscellaneous

#### Load data from file

In [44]:
filedata_1 = np.genfromtxt('test.txt', delimiter=',', dtype='int16')
print(filedata_1)

# or 
filedata_2 = np.genfromtxt('test.txt', delimiter=',')
filedata_2 = filedata_2.astype('int16')
print(filedata_2)

[[1 2 3 4 5 6 7 8 9 0]
 [1 2 3 4 5 6 7 8 9 0]
 [1 2 3 4 5 6 7 8 9 0]]
[[1 2 3 4 5 6 7 8 9 0]
 [1 2 3 4 5 6 7 8 9 0]
 [1 2 3 4 5 6 7 8 9 0]]


#### Boolean masking and advanced indexing

In [45]:
filedata_2 > 5

array([[False, False, False, False, False,  True,  True,  True,  True,
        False],
       [False, False, False, False, False,  True,  True,  True,  True,
        False],
       [False, False, False, False, False,  True,  True,  True,  True,
        False]])

In [46]:
filedata_2 [filedata_2 > 5]

array([6, 7, 8, 9, 6, 7, 8, 9, 6, 7, 8, 9], dtype=int16)

In [47]:
# you can index with list in numpy
a = np.array([1,2,3,4,5])
a[[0,2,4]]

array([1, 3, 5])

In [48]:
# finds any value with condition according to axis
np.any(filedata_2 > 5, axis=0)

array([False, False, False, False, False,  True,  True,  True,  True,
       False])

In [49]:
# finds if all values satisfy the condition according to axis
np.all(filedata_2 > 5, axis=0)

array([False, False, False, False, False,  True,  True,  True,  True,
       False])

In [50]:
# can pass multiple conditions
((filedata_2 > 3) & (filedata_2 < 7))

array([[False, False, False,  True,  True,  True, False, False, False,
        False],
       [False, False, False,  True,  True,  True, False, False, False,
        False],
       [False, False, False,  True,  True,  True, False, False, False,
        False]])